# ________  ________ ________  ________   ________      ___    ___ _________  ________  ________
#|\   ___ \|\  _____\\   __  \|\   ___  \|\   ____\    |\  \  /  /|\___   ___\\   __  \|\   __  \
#\ \  \_|\ \ \  \__/\ \  \|\  \ \  \\ \  \ \  \___|    \ \  \/  / ||___ \  \_\ \  \|\  \ \  \|\ /_
# \ \  \ \\ \ \   __\\ \   __  \ \  \\ \  \ \  \        \ \    / /     \ \  \ \ \   __  \ \   __  \
#  \ \  \_\\ \ \  \_| \ \  \ \  \ \  \\ \  \ \  \____    \/  /  /       \ \  \ \ \  \ \  \ \  \|\  \
#   \ \_______\ \__\   \ \__\ \__\ \__\\ \__\ \_______\__/  / /          \ \__\ \ \__\ \__\ \_______\
#    \|_______|\|__|    \|__|\|__|\|__| \|__|\|_______|\___/ /            \|__|  \|__|\|__|\|_______|
#                                                     \|___|/
#
# Legal Note:
#

#
# (C) 2018 David Kraus. All rights reserved.
#####################################################################################################

tablist:
  header: 'This is the header'
  footer: 'This is the footer'